# This is a basic workflow that is manually triggered

name: pixiv antics

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      mode:
        description: 'Dump by Artist ID (artist), Tags (tags), or Artist ID and Tags combined (combined)? '
        default: 'artist'
        required: true
      parameters:
        description: 'curl parameters used by pixiv: '
        default: ''
        required: true
      artist:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Artist ID: '
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: false
      tags:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Tags: '
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "dump"
  dump:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout codes
      uses: actions/checkout@v3

    - name: Start Dumping
      run: |
        echo "${{ github.event.inputs.parameters }}" > parameters.txt
        ls
        echo "received arguments: ${{ github.event.inputs.mode }}, ${{ github.event.inputs.artist }}, ${{ github.event.inputs.tags }}"
        
